"""Generate a PyInstaller ``--version-file`` from ``version.APP_VERSION``.

Without a Win32 version resource, the built exe has empty CompanyName /
ProductName / FileDescription. Task Manager reads FileDescription for its "Name"
column, so an empty one falls back to the raw filename (and a source run shows
the interpreter's own resource, which literally says "Python"). Generating the
resource from ``version.py`` keeps it from drifting out of sync with the tag the
release workflow enforces.

Usage:
    python release/make_version_file.py <output-path>
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import version  # noqa: E402  (path shim above must run first)

COMPANY_NAME = "Rainette Music"
PRODUCT_NAME = "Rainette Music"
FILE_DESCRIPTION = "Rainette Music"
LEGAL_COPYRIGHT = "© Rainette Music"
ORIGINAL_FILENAME = "RainetteMusic.exe"
INTERNAL_NAME = "RainetteMusic"

# US English, Unicode codepage — the langID/charsetID pair the string block
# below (040904B0) encodes.
LANG_ID = 0x0409
CHARSET_ID = 0x04B0

_TEMPLATE = """\
# Auto-generated by release/make_version_file.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '{lang_charset}',
        [
          StringStruct('CompanyName', '{company}'),
          StringStruct('FileDescription', '{description}'),
          StringStruct('FileVersion', '{version_str}'),
          StringStruct('InternalName', '{internal}'),
          StringStruct('LegalCopyright', '{copyright}'),
          StringStruct('OriginalFilename', '{original}'),
          StringStruct('ProductName', '{product}'),
          StringStruct('ProductVersion', '{version_str}'),
        ],
      ),
    ]),
    VarFileInfo([VarStruct('Translation', [{lang_id}, {charset_id}])]),
  ],
)
"""


def _version_tuple() -> tuple[int, int, int, int]:
    parts = list(version.parse_version(version.APP_VERSION))[:3]
    while len(parts) < 3:
        parts.append(0)
    return (parts[0], parts[1], parts[2], 0)


def render() -> str:
    tup = _version_tuple()
    return _TEMPLATE.format(
        version_tuple=tup,
        version_str=".".join(str(n) for n in tup),
        lang_charset=f"{LANG_ID:04x}{CHARSET_ID:04x}",
        lang_id=LANG_ID,
        charset_id=CHARSET_ID,
        company=COMPANY_NAME,
        description=FILE_DESCRIPTION,
        internal=INTERNAL_NAME,
        copyright=LEGAL_COPYRIGHT,
        original=ORIGINAL_FILENAME,
        product=PRODUCT_NAME,
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        sys.stderr.write("usage: make_version_file.py <output-path>\n")
        return 2
    output = Path(argv[1])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(), encoding="utf-8")
    sys.stdout.write(f"Wrote version resource for {version.APP_VERSION} to {output}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
